services:
  postgres:
    image: postgres:16
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/user_db
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-service-app:
    build:
      context: ../../../../
      dockerfile:  apps/backend/user-service/ci/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/user_db
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - shared-data:/shared
    networks:
      - custom_network
    command: >
      sh -c "npx prisma migrate deploy --schema=./apps/backend/user-service/prisma/schema.prisma &&
             node apps/backend/user-service/dist/main.js"


volumes:
  shared-data:
    driver: local
  postgres_data:




networks:
  custom_network:
    name: ec2-user_user-network
