services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - custom_network

  user-service:
    image: ${AWS_ECR_REGISTRY}/messaging/api-gateway-dev:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/user_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
      - POSTGRES_HOST=localhost

    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - shared-data:/shared
    networks:
      - custom_network


volumes:
  shared-data:
    driver: local
  postgres_data:




networks:
  custom_network:
    name: ec2-user_user-network
