services:
  api-gateway:
    image: ${AWS_ECR_REGISTRY}/messaging/api-gateway-dev:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "3000:3000"
    volumes:
      - shared-data:/shared
    networks:
      - custom_network

volumes:
  shared-data:
    driver: local

networks:
  custom_network:
    name: ec2-user_gateway-network
