services:
 api-gateway-app:
    image:
      "${AWS_ECR_REGISTRY}/dev:latest"  # Use the pulled image from ECR
    ports:
      - "3000:3000"
    command: >
      sh -c "node apps/backend/api-gateway/dist/main.js"

