services:
 nestjs-app:
    build:
      context: ../../../../
      dockerfile:  apps/backend/api-gateway/ci/Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: >
      sh -c "node apps/backend/api-gateway/dist/main.js"

volumes:
  postgres_data:
