name: Api Gateway

on:
  push:
    branches: [ "master" ]
    paths:
      - 'apps/backend/api-gateway/**'
      - '.github/workflows/api-gateway.yml'
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up AWS credentials using configure-aws-credentials action
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-ecr-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.AWS_ECR_REGISTRY }}/dev:latest . --file apps/backend/api-gateway/ci/Dockerfile
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/dev:latest



      # Set up SSH to connect to EC2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_DEV }}" > ~/.ssh/private.pem
          chmod 600 ~/.ssh/private.pem
          ssh-keyscan -H ec2-52-66-173-198.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      # Deploy Application to EC2
      - name: Deploy Application to EC2
        run: |
          ssh -i ~/.ssh/private.pem ec2-user@ec2-52-66-173-198.ap-south-1.compute.amazonaws.com '
            # Pull the latest Docker image from ECR
            docker pull ${{ secrets.AWS_ECR_REGISTRY }}/dev:latest
            # Restart Docker containers using Docker Compose
            sudo docker-compose -f /apps/backend/api-gateway/ci/docker-compose.yml down
            sudo docker-compose -f /apps/backend/api-gateway/ci/docker-compose.yml up -d
          '