name: Api Gateway

on:
  push:
    branches: [ "master" ]
    paths:
      - 'apps/backend/api-gateway/**'
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file apps/backend/api-gateway/ci/Dockerfile --tag api-gateway-dev:$(date +%s)
