name: Api Gateway
on:
  push:
    branches: [ "master" ]
    paths:
      - 'apps/backend/api-gateway/**'
      - '.github/workflows/api-gateway.yml'
      - '.github/workflows/reusable-build.yml'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app-path: apps/backend/api-gateway
      image-name: messaging/api-gateway-dev
      app-name: api-gateway
    secrets: inherit
