name: User Service

on:
  push:
    branches: [ "master" ]
    paths:
      - 'apps/backend/user-service/**'
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file apps/backend/user-service/ci/Dockerfile --tag user-service-dev:$(date +%s)
