name: User service
on:
  push:
    branches: [ "master" ]
    paths:
      - 'apps/backend/user-service/**'
      - '.github/workflows/user-service.yml'
      - '.github/workflows/reusable-build.yml'
      - 'packages/**'
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app-path: apps/backend/user-service
      image-name: messaging/user-service-dev
      app-name: user-service
    secrets: inherit
